apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-server
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: qa
  project: default
  source:
    repoURL: 'https://github.com/rcbop/kubemaster.git'
    path: k8s/qa/nginx
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
